### ISSUE TITLE
Eligible student cannot access the invitation to accept

### ISSUE THREAD

**Issue by TuckKau** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#59]
**What is the e-mail address you are using to login to xehub**
kaus@pdx.edu

**What is your chapter number and name**
Portland State University Chapter #131

**Describe the bug**
One student who wants to become a XE member is having trouble accessing the invitation to join. Her name is Ashley N Arries. When she clicks on the link to the application, she is being brought to the XEHUB Home Page instead.

**To Reproduce**
1. Click on the link to submit the XE new member application
2. See the XEHUB Home Page

**Expected behavior**
When she clicks on the link, she should see the window shown below to register as a new member.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/84044842/117882063-cebb8d80-b25e-11eb-9fee-b15a27f774c1.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by brunofvalli** [comment]
Ashley has already registered using the link. 
The e-mailed link can only be used once.

I have changed the application to give a better error message when she attempts to use the link.

She should get this message now:
![image](https://user-images.githubusercontent.com/5949285/118349940-6a782280-b519-11eb-8187-a02c7cad0697.png)

You can try this link that was sent to her on the last e-mail message:
[hidden link]

To get the same error message you cannot be logged into XEHub.

She would need to either login using the account that has already been created, or she can reset her password by following the "Forgot your password?" link under the "Log In" screen:

![image](https://user-images.githubusercontent.com/5949285/118349965-ab703700-b519-11eb-8956-c9a3a7e4d3a1.png)

**Comment by TuckKau** [comment]
So it looks like that didn't solve the issue. The XEHUB already recognizes that she is in the system, which doesn't make sense because she never was directed to the text window (shown in my first post) in any of the invitations I either sent or resent to her. Every invite link she clicked on directed her to the XEHUB Log in screen, which shouldn't happen because according to my XEHUB, she is not shown in the 'Invitation Accepted' form. Because she is technically in the system already, is there a way for her invitation to be accepted in a different way? I don't know if it was a mistake somewhere on my part or her part, but I just don't get why she was never directed to that text window to register when all of my other new members had no issues accessing it and filling it out. Thanks!

**Comment by brunofvalli** [comment]
The problem is she has registered, but she never logged in. I can reset her account and she would get an invitation link again. I am going to do that instead. I will let you know once I do.

**Comment by brunofvalli** [comment]
I have deleted her registration and re-invited her. It should work now.
She should have received another invitation.

**Comment by TuckKau** [comment]
So she tried clicking on the new link that you sent her and it still directed her to the login page with the error message that you previously mentioned. For some reason even though you deleted her registration, she is still not being directed to the text window that everyone else is usually immediately directed to.

**Comment by brunofvalli** [comment]
Ok, now I see what I messed up there. It would work now. Please ask her to try again.

**Comment by TuckKau** [comment]
It worked! She is now in the 'Officer Approved' tab. Thank you so much for your help.
